module.exports = [
  {
    model: 'chatbot',
    documents: [
      [
        {activate: 1, input: 'o nariz do Pinóquio, quando ele cresce? ', output: 'quando ele mente'},
        {activate: 1, input: 'Cristo Redentor, fica em qual cidade? ', output: 'No Rio de Janeiro'},
        {activate: 1, input: 'alfabeto, tem Quantas letras? ', output: '26 letras'},
        {activate: 1, input: 'está no meio do ovo? ', output: 'a letra V'},
        {activate: 1, input: 'nasce grande e morre pequeno? ', output: 'o lápis'},
        {activate: 1, input: 'o céu que não tem estrelas? ', output: 'o céu da boca'},
        {activate: 1, input: 'profissão de quem apaga o fogo? ', output: 'bombeiro'},
        {activate: 1, input: 'A primavera acontece depois de qual estação do ano? ', output: 'do inverno'},
        {activate: 1, input: 'abelhas fabricam, qual alimento? ', output: 'mel'},
        {activate: 1, input: 'Quantos meses tem 1 ano? ', output: '12 meses'},
        {activate: 1, input: 'boneca de pano mais famosa do Brasil? ', output: 'a Emília, a personagem de Monteiro Lobato'},
        {activate: 1, input: 'A mistura das cores vermelho e branco forma qual cor? ', output: 'a cor rosa'},
        {activate: 1, input: 'história da menina que usava um capuz vermelho? ', output: 'Chapeuzinho Vermelho'},
        {activate: 1, input: 'ingredientes do slime? ', output: 'cola e água'},
        {activate: 1, input: 'com a letra B, Um programa de TV? ', output: ' Barney, Big Brother Brasil, Breaking Bad'},
        {activate: 1, input: 'estados tem o Brasil, Quantos são? ', output: ' 26 estados'},
        {activate: 1, input: 'futebol do Brasil, Quais as duas maiores torcidas de ? ', output: ' Corinthians e Flamengo'},
        {activate: 1, input: 'Mona Lisa, Quem pintou? ', output: ' Leonardo da Vinci'},
        {activate: 1, input: 'hashtag #TBT, O que significa a ? ', output: ' Throw back Thursday'},
        {activate: 1, input: 'Atenas, Onde fica ', output: ' na Grécia'},
        {activate: 1, input: 'tomate é um legume ou uma fruta? ', output: ' uma fruta'},
        {activate: 1, input: 'idioma falado na Austrália? ', output: ' inglês'},
        {activate: 1, input: 'ITI Malia, O que significa? ', output: ' ixi Maria'},
        {activate: 1, input: 'Dia das Mães Em qual mês se comemora o ? ', output: ' maio'},
        {activate: 1, input: 'cachorro-quente em inglês, Como se diz? ', output: ' hot-dog'},
        {activate: 1, input: 'bandeira do Brasil quais são as cores? ', output: ' verde, amarelo, azul e branco'},
        {activate: 1, input: 'canal do Silvio Santos? ', output: ' SBT'},
        {activate: 1, input: 'escola de samba é a mais conhecida pelas cores verde e rosa? ', output: ' Estação Primeira de Mangueira'},
        {activate: 1, input: 'primeira capital do Brasil? ', output: ' Salvador'},
      ],
    ],
  },
];
